# Generated by Django 4.0.4 on 2022-05-04 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='course_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_data.course_data'),
        ),
    ]
