# Generated by Django 4.0.4 on 2022-05-05 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0002_student_data_course_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='course_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_data.course_data'),
        ),
    ]
