# Generated by Django 4.0.4 on 2022-05-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0003_alter_student_data_course_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='st_dob',
            field=models.CharField(max_length=30),
        ),
    ]
